//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BombaJob {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BombaJob.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BombaJob.
        /// </summary>
        public static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-App Email.
        /// </summary>
        public static string conf_InAppEmail {
            get {
                return ResourceManager.GetString("conf_InAppEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Synchronization.
        /// </summary>
        public static string conf_InitSync {
            get {
                return ResourceManager.GetString("conf_InitSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Search.
        /// </summary>
        public static string conf_OnlineSearch {
            get {
                return ResourceManager.GetString("conf_OnlineSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember private data.
        /// </summary>
        public static string conf_PrivateData {
            get {
                return ResourceManager.GetString("conf_PrivateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Categories.
        /// </summary>
        public static string conf_ShowCategories {
            get {
                return ResourceManager.GetString("conf_ShowCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet connection at the moment. Try again later..
        /// </summary>
        public static string error_NoInternet {
            get {
                return ResourceManager.GetString("error_NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everywhere.
        /// </summary>
        public static string freelance_all {
            get {
                return ResourceManager.GetString("freelance_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Project/Freelance.
        /// </summary>
        public static string freelance_no {
            get {
                return ResourceManager.GetString("freelance_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Project/Freelance.
        /// </summary>
        public static string freelance_only {
            get {
                return ResourceManager.GetString("freelance_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will close the app and will open IE. Are you sure?.
        /// </summary>
        public static string linkClicked {
            get {
                return ResourceManager.GetString("linkClicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About BombaJob.bg.
        /// </summary>
        public static string menu_About {
            get {
                return ResourceManager.GetString("menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string menu_Categories {
            get {
                return ResourceManager.GetString("menu_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers.
        /// </summary>
        public static string menu_Jobs {
            get {
                return ResourceManager.GetString("menu_Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newest.
        /// </summary>
        public static string menu_Newest {
            get {
                return ResourceManager.GetString("menu_Newest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers.
        /// </summary>
        public static string menu_Offers {
            get {
                return ResourceManager.GetString("menu_Offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string menu_People {
            get {
                return ResourceManager.GetString("menu_People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string menu_Post {
            get {
                return ResourceManager.GetString("menu_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string menu_Search {
            get {
                return ResourceManager.GetString("menu_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string menu_Settings {
            get {
                return ResourceManager.GetString("menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization.
        /// </summary>
        public static string menu_Sync {
            get {
                return ResourceManager.GetString("menu_Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string monthFull_1 {
            get {
                return ResourceManager.GetString("monthFull_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string monthFull_10 {
            get {
                return ResourceManager.GetString("monthFull_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string monthFull_11 {
            get {
                return ResourceManager.GetString("monthFull_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string monthFull_12 {
            get {
                return ResourceManager.GetString("monthFull_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string monthFull_2 {
            get {
                return ResourceManager.GetString("monthFull_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string monthFull_3 {
            get {
                return ResourceManager.GetString("monthFull_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string monthFull_4 {
            get {
                return ResourceManager.GetString("monthFull_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string monthFull_5 {
            get {
                return ResourceManager.GetString("monthFull_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string monthFull_6 {
            get {
                return ResourceManager.GetString("monthFull_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string monthFull_7 {
            get {
                return ResourceManager.GetString("monthFull_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string monthFull_8 {
            get {
                return ResourceManager.GetString("monthFull_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string monthFull_9 {
            get {
                return ResourceManager.GetString("monthFull_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jan.
        /// </summary>
        public static string monthShort_1 {
            get {
                return ResourceManager.GetString("monthShort_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oct.
        /// </summary>
        public static string monthShort_10 {
            get {
                return ResourceManager.GetString("monthShort_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nov.
        /// </summary>
        public static string monthShort_11 {
            get {
                return ResourceManager.GetString("monthShort_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dec.
        /// </summary>
        public static string monthShort_12 {
            get {
                return ResourceManager.GetString("monthShort_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feb.
        /// </summary>
        public static string monthShort_2 {
            get {
                return ResourceManager.GetString("monthShort_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mar.
        /// </summary>
        public static string monthShort_3 {
            get {
                return ResourceManager.GetString("monthShort_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apr.
        /// </summary>
        public static string monthShort_4 {
            get {
                return ResourceManager.GetString("monthShort_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string monthShort_5 {
            get {
                return ResourceManager.GetString("monthShort_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jun.
        /// </summary>
        public static string monthShort_6 {
            get {
                return ResourceManager.GetString("monthShort_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jul.
        /// </summary>
        public static string monthShort_7 {
            get {
                return ResourceManager.GetString("monthShort_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aug.
        /// </summary>
        public static string monthShort_8 {
            get {
                return ResourceManager.GetString("monthShort_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sept.
        /// </summary>
        public static string monthShort_9 {
            get {
                return ResourceManager.GetString("monthShort_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Categories..
        /// </summary>
        public static string noCategories {
            get {
                return ResourceManager.GetString("noCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Offers..
        /// </summary>
        public static string noOffers {
            get {
                return ResourceManager.GetString("noOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boom!.
        /// </summary>
        public static string offer_Boom {
            get {
                return ResourceManager.GetString("offer_Boom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        public static string offer_Category {
            get {
                return ResourceManager.GetString("offer_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I work in:.
        /// </summary>
        public static string offer_category_title {
            get {
                return ResourceManager.GetString("offer_category_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string offer_Company_Email {
            get {
                return ResourceManager.GetString("offer_Company_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company advantages:.
        /// </summary>
        public static string offer_Company_Negativ {
            get {
                return ResourceManager.GetString("offer_Company_Negativ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position  description:.
        /// </summary>
        public static string offer_Company_Positiv {
            get {
                return ResourceManager.GetString("offer_Company_Positiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position title:.
        /// </summary>
        public static string offer_Company_Title {
            get {
                return ResourceManager.GetString("offer_Company_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project/Freelance:.
        /// </summary>
        public static string offer_FreelanceYn {
            get {
                return ResourceManager.GetString("offer_FreelanceYn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email:.
        /// </summary>
        public static string offer_Human_Email {
            get {
                return ResourceManager.GetString("offer_Human_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills:.
        /// </summary>
        public static string offer_Human_Negativ {
            get {
                return ResourceManager.GetString("offer_Human_Negativ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problems:.
        /// </summary>
        public static string offer_Human_Positiv {
            get {
                return ResourceManager.GetString("offer_Human_Positiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title of your resume:.
        /// </summary>
        public static string offer_Human_Title {
            get {
                return ResourceManager.GetString("offer_Human_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string offer_iam_company {
            get {
                return ResourceManager.GetString("offer_iam_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human.
        /// </summary>
        public static string offer_iam_human {
            get {
                return ResourceManager.GetString("offer_iam_human", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am.
        /// </summary>
        public static string offer_iam_title {
            get {
                return ResourceManager.GetString("offer_iam_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string offer_Message {
            get {
                return ResourceManager.GetString("offer_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message is empty..
        /// </summary>
        public static string offer_Message_Empty {
            get {
                return ResourceManager.GetString("offer_Message_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is something missing....
        /// </summary>
        public static string offer_MissingReqFields {
            get {
                return ResourceManager.GetString("offer_MissingReqFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send message.
        /// </summary>
        public static string offer_sendMessage {
            get {
                return ResourceManager.GetString("offer_sendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You!.
        /// </summary>
        public static string offer_ThankYou {
            get {
                return ResourceManager.GetString("offer_ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers:.
        /// </summary>
        public static string offers {
            get {
                return ResourceManager.GetString("offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string popup_Cancel {
            get {
                return ResourceManager.GetString("popup_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string popup_OK {
            get {
                return ResourceManager.GetString("popup_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project/Freelance.
        /// </summary>
        public static string search_Freelance {
            get {
                return ResourceManager.GetString("search_Freelance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string search_Results {
            get {
                return ResourceManager.GetString("search_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string search_Search {
            get {
                return ResourceManager.GetString("search_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to email....
        /// </summary>
        public static string share_Email_Desc {
            get {
                return ResourceManager.GetString("share_Email_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BombaJob.bg - check that offer.
        /// </summary>
        public static string share_Email_Subject {
            get {
                return ResourceManager.GetString("share_Email_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string shortCompany {
            get {
                return ResourceManager.GetString("shortCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.
        /// </summary>
        public static string shortHuman {
            get {
                return ResourceManager.GetString("shortHuman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string weekday_1 {
            get {
                return ResourceManager.GetString("weekday_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string weekday_2 {
            get {
                return ResourceManager.GetString("weekday_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string weekday_3 {
            get {
                return ResourceManager.GetString("weekday_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string weekday_4 {
            get {
                return ResourceManager.GetString("weekday_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string weekday_5 {
            get {
                return ResourceManager.GetString("weekday_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string weekday_6 {
            get {
                return ResourceManager.GetString("weekday_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string weekday_7 {
            get {
                return ResourceManager.GetString("weekday_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
