//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BombaJob {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BombaJob.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BombaJob.
        /// </summary>
        public static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В момента няма интернет връзка. Опитайте по-късно пак..
        /// </summary>
        public static string error_NoInternet {
            get {
                return ResourceManager.GetString("error_NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Навсякъде.
        /// </summary>
        public static string freelance_all {
            get {
                return ResourceManager.GetString("freelance_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без Проект/Freelance.
        /// </summary>
        public static string freelance_no {
            get {
                return ResourceManager.GetString("freelance_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Само Проект/Freelance.
        /// </summary>
        public static string freelance_only {
            get {
                return ResourceManager.GetString("freelance_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Това действие ще затвори текущото приложение и ще отвори Internet Explorer. Сигурни ли сте?.
        /// </summary>
        public static string linkClicked {
            get {
                return ResourceManager.GetString("linkClicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зареждане....
        /// </summary>
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За BombJob.bg.
        /// </summary>
        public static string menu_About {
            get {
                return ResourceManager.GetString("menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категории.
        /// </summary>
        public static string menu_Categories {
            get {
                return ResourceManager.GetString("menu_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оферти.
        /// </summary>
        public static string menu_Jobs {
            get {
                return ResourceManager.GetString("menu_Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нови.
        /// </summary>
        public static string menu_Newest {
            get {
                return ResourceManager.GetString("menu_Newest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оферти.
        /// </summary>
        public static string menu_Offers {
            get {
                return ResourceManager.GetString("menu_Offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хора.
        /// </summary>
        public static string menu_People {
            get {
                return ResourceManager.GetString("menu_People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Публикувай.
        /// </summary>
        public static string menu_Post {
            get {
                return ResourceManager.GetString("menu_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Търси.
        /// </summary>
        public static string menu_Search {
            get {
                return ResourceManager.GetString("menu_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        public static string menu_Settings {
            get {
                return ResourceManager.GetString("menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Синхронизация.
        /// </summary>
        public static string menu_Sync {
            get {
                return ResourceManager.GetString("menu_Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Януари.
        /// </summary>
        public static string monthFull_1 {
            get {
                return ResourceManager.GetString("monthFull_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Октомври.
        /// </summary>
        public static string monthFull_10 {
            get {
                return ResourceManager.GetString("monthFull_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ноември.
        /// </summary>
        public static string monthFull_11 {
            get {
                return ResourceManager.GetString("monthFull_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Декември.
        /// </summary>
        public static string monthFull_12 {
            get {
                return ResourceManager.GetString("monthFull_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Февруари.
        /// </summary>
        public static string monthFull_2 {
            get {
                return ResourceManager.GetString("monthFull_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Март.
        /// </summary>
        public static string monthFull_3 {
            get {
                return ResourceManager.GetString("monthFull_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Април.
        /// </summary>
        public static string monthFull_4 {
            get {
                return ResourceManager.GetString("monthFull_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Май.
        /// </summary>
        public static string monthFull_5 {
            get {
                return ResourceManager.GetString("monthFull_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Юни.
        /// </summary>
        public static string monthFull_6 {
            get {
                return ResourceManager.GetString("monthFull_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Юли.
        /// </summary>
        public static string monthFull_7 {
            get {
                return ResourceManager.GetString("monthFull_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Август.
        /// </summary>
        public static string monthFull_8 {
            get {
                return ResourceManager.GetString("monthFull_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Септември.
        /// </summary>
        public static string monthFull_9 {
            get {
                return ResourceManager.GetString("monthFull_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Яну.
        /// </summary>
        public static string monthShort_1 {
            get {
                return ResourceManager.GetString("monthShort_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Окт.
        /// </summary>
        public static string monthShort_10 {
            get {
                return ResourceManager.GetString("monthShort_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ное.
        /// </summary>
        public static string monthShort_11 {
            get {
                return ResourceManager.GetString("monthShort_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дек.
        /// </summary>
        public static string monthShort_12 {
            get {
                return ResourceManager.GetString("monthShort_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фев.
        /// </summary>
        public static string monthShort_2 {
            get {
                return ResourceManager.GetString("monthShort_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Март.
        /// </summary>
        public static string monthShort_3 {
            get {
                return ResourceManager.GetString("monthShort_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Апр.
        /// </summary>
        public static string monthShort_4 {
            get {
                return ResourceManager.GetString("monthShort_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Май.
        /// </summary>
        public static string monthShort_5 {
            get {
                return ResourceManager.GetString("monthShort_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Юни.
        /// </summary>
        public static string monthShort_6 {
            get {
                return ResourceManager.GetString("monthShort_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Юли.
        /// </summary>
        public static string monthShort_7 {
            get {
                return ResourceManager.GetString("monthShort_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авг.
        /// </summary>
        public static string monthShort_8 {
            get {
                return ResourceManager.GetString("monthShort_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Септ.
        /// </summary>
        public static string monthShort_9 {
            get {
                return ResourceManager.GetString("monthShort_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Няма категории..
        /// </summary>
        public static string noCategories {
            get {
                return ResourceManager.GetString("noCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Няма оферти..
        /// </summary>
        public static string noOffers {
            get {
                return ResourceManager.GetString("noOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бум!.
        /// </summary>
        public static string offer_Boom {
            get {
                return ResourceManager.GetString("offer_Boom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория:.
        /// </summary>
        public static string offer_Category {
            get {
                return ResourceManager.GetString("offer_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Работя в:.
        /// </summary>
        public static string offer_category_title {
            get {
                return ResourceManager.GetString("offer_category_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email за връзка:.
        /// </summary>
        public static string offer_Company_Email {
            get {
                return ResourceManager.GetString("offer_Company_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предимства на фирмата:.
        /// </summary>
        public static string offer_Company_Negativ {
            get {
                return ResourceManager.GetString("offer_Company_Negativ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание на позицията:.
        /// </summary>
        public static string offer_Company_Positiv {
            get {
                return ResourceManager.GetString("offer_Company_Positiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заглавие на позицията:.
        /// </summary>
        public static string offer_Company_Title {
            get {
                return ResourceManager.GetString("offer_Company_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проект/Freelance:.
        /// </summary>
        public static string offer_FreelanceYn {
            get {
                return ResourceManager.GetString("offer_FreelanceYn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вашият email:.
        /// </summary>
        public static string offer_Human_Email {
            get {
                return ResourceManager.GetString("offer_Human_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Умения:.
        /// </summary>
        public static string offer_Human_Negativ {
            get {
                return ResourceManager.GetString("offer_Human_Negativ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проблем:.
        /// </summary>
        public static string offer_Human_Positiv {
            get {
                return ResourceManager.GetString("offer_Human_Positiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заглавие на резюмето ви:.
        /// </summary>
        public static string offer_Human_Title {
            get {
                return ResourceManager.GetString("offer_Human_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фирма.
        /// </summary>
        public static string offer_iam_company {
            get {
                return ResourceManager.GetString("offer_iam_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Човек.
        /// </summary>
        public static string offer_iam_human {
            get {
                return ResourceManager.GetString("offer_iam_human", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аз съм.
        /// </summary>
        public static string offer_iam_title {
            get {
                return ResourceManager.GetString("offer_iam_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Има нещо изпуснато....
        /// </summary>
        public static string offer_MissingReqFields {
            get {
                return ResourceManager.GetString("offer_MissingReqFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Благодарим ви!.
        /// </summary>
        public static string offer_ThankYou {
            get {
                return ResourceManager.GetString("offer_ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оферти:.
        /// </summary>
        public static string offers {
            get {
                return ResourceManager.GetString("offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проект/Freelance.
        /// </summary>
        public static string search_Freelance {
            get {
                return ResourceManager.GetString("search_Freelance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Търси.
        /// </summary>
        public static string search_Search {
            get {
                return ResourceManager.GetString("search_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ф.
        /// </summary>
        public static string shortCompany {
            get {
                return ResourceManager.GetString("shortCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ч.
        /// </summary>
        public static string shortHuman {
            get {
                return ResourceManager.GetString("shortHuman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Понеделник.
        /// </summary>
        public static string weekday_1 {
            get {
                return ResourceManager.GetString("weekday_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вторник.
        /// </summary>
        public static string weekday_2 {
            get {
                return ResourceManager.GetString("weekday_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сряда.
        /// </summary>
        public static string weekday_3 {
            get {
                return ResourceManager.GetString("weekday_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Четвъртък.
        /// </summary>
        public static string weekday_4 {
            get {
                return ResourceManager.GetString("weekday_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Петък.
        /// </summary>
        public static string weekday_5 {
            get {
                return ResourceManager.GetString("weekday_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Събота.
        /// </summary>
        public static string weekday_6 {
            get {
                return ResourceManager.GetString("weekday_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неделя.
        /// </summary>
        public static string weekday_7 {
            get {
                return ResourceManager.GetString("weekday_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
