//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BombaJob {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BombaJob.Utilities.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В момента няма интернет връзка. Опитайте по-късно пак..
        /// </summary>
        public static string error_NoInternet {
            get {
                return ResourceManager.GetString("error_NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Това действие ще затвори текущото приложение и ще отвори Internet Explorer. Сигурни ли сте?.
        /// </summary>
        public static string linkClicked {
            get {
                return ResourceManager.GetString("linkClicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зареждане....
        /// </summary>
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За BombJob.bg.
        /// </summary>
        public static string menu_About {
            get {
                return ResourceManager.GetString("menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оферти.
        /// </summary>
        public static string menu_Jobs {
            get {
                return ResourceManager.GetString("menu_Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нови.
        /// </summary>
        public static string menu_Newest {
            get {
                return ResourceManager.GetString("menu_Newest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хора.
        /// </summary>
        public static string menu_People {
            get {
                return ResourceManager.GetString("menu_People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Публикувай.
        /// </summary>
        public static string menu_Post {
            get {
                return ResourceManager.GetString("menu_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Търси.
        /// </summary>
        public static string menu_Search {
            get {
                return ResourceManager.GetString("menu_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        public static string menu_Settings {
            get {
                return ResourceManager.GetString("menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Синхронизация.
        /// </summary>
        public static string menu_Sync {
            get {
                return ResourceManager.GetString("menu_Sync", resourceCulture);
            }
        }
    }
}
